############################
## CHANGE THESE
############################

baseURL: "https://thepurpleplatypus.github.io/DigitalGarden"
title: Digital Garden

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
